#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# export PATH
# typeset -a paths result
# paths=($path)
#
# while [[ ${#paths} -gt 0 ]]; do
#   p="${paths[1]}"
#   shift paths
#   [[ -z ${paths[(r)$p]} ]] && result+="$p"
# done
#
# export PATH=${(j+:+)result}

# The PATH is cleared first and then rebuilt. The result is far less duplication of directories.
if [ -x /usr/libexec/path_helper ]; then
    PATH=''
    eval `/usr/libexec/path_helper -s`
fi

# if rbenv is present, configure it for use
if which rbenv &> /dev/null; then
    # Put the rbenv entry at the front of the line
    export PATH="$HOME/.rbenv/bin:$PATH"

    # enable shims and auto-completion
    eval "$(rbenv init -)"
fi
